### ISSUE TITLE
Very nice Plugin! But it throws a FatalError. Do you have any solutions? Thanks.

### ISSUE THREAD

**Issue by fabianwnk** [UseMuffin/Crypt#2]
Error message is:

> Fatal error: Call to a member function has() on array in /Applications/xxx/htdocs/xxx/xxx/vendor/muffin/crypt/src/Model/Behavior/CryptBehavior.php on line 102

The Code:

```
Line 101:  if (($options['fields'] && !in_array($field, (array)$options['fields']))
Line 102:       || !$row->has($field)
```

My Config:

```
$this->addBehavior('Muffin/Crypt.Crypt', [
            'fields' => ['first_name'],
            'strategy' => '\Muffin\Crypt\Model\Behavior\Strategy\DefaultStrategy',
            'implementedEvents' => [
                'Model.beforeSave' => 'beforeSave',
                'Model.beforeFind' => 'beforeFind',
            ]
        ]);
```

Thanks.

**Comment by jadb** [comment]
Are you running it with `hydrate(false)`?

**Comment by jadb** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by shoesole** [comment]
I'm still running into this issue on the same line of code with a very similar setup (specifically when the "implementedEvents' contains the 'Model.beforeFind'. The error occurs for me when saving a table that is related to the model which contains encrypted data. In my case the rules checker $rules->existsIn() function seems to cause this issue.

**Comment by shoesole** [comment]
More info, if I have an "employee" model with encrypted fields in it, and then I'm saving a new record in the related table "vacation_requests" which has a foreign key of "employe_id" and the "VacationRequestsTable.php" file has a buildRule which looks like:

```
public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['employee_id'], 'Employees'));

        return $rules;
    } 
```

Then the error above displays for me. Short term, I can disable the rule checker, but I'd prefer not to do that if possible.

**Comment by chrisShick** [comment]
I am also getting this same error. I am running 3.4.5.

**Comment by chrisShick** [comment]
I did some debugging and the row is being turned into an array. I am also using the CRUD plugin if that makes any difference.

**Comment by chrisShick** [comment]
I believe the solution to this issue is to check for an empty result set. I have created a pull request 
https://github.com/UseMuffin/Crypt/pull/5
