### ISSUE TITLE
Unable to use the Defaults for CakePHP 3.4

### ISSUE THREAD

**Issue by shoesole** [UseMuffin/Crypt#3]
Hello, It appears that CakePHP 3.4 changed to use Configure::consume('Security.salt'); in the bootstrap.php file. This means that you can no longer use Configure::read('Security.salt') in order to get the default value. Not a huge issue (as a person can simply call new DefaultStrategy(Security::salt()) but would be nice to not need to implement the strategy if not planning to change from the default.

**Comment by ADmad** [comment]
Pull request welcome.
